### ISSUE TITLE
ClassLabel or Value

### ISSUE THREAD

**Issue by kdsull** [rickiepark/nlp-with-transformers#2]
2. Classification의 18번 셀의 경우 암만 돌려봐도 'ClassLabel'이 아니고 'Value'로 나오는 건 어떤 이유인지 궁금합니다. 그 다음 
셀로 내려가질 못 하는군요...

**Comment by rickiepark** [comment]
안녕하세요. datasets 버전을 2.10.x로 고정하고 테스트해 보세요. 2.11 버전부터 Features 속성을 바꿀 수 없어서 발생하는 문제인데 어떤 이유인지는 제가 정확하게 파악하지 못했습니다. 감사합니다.

**Comment by tonioyoon** [comment]
저는 이렇게 바꾸니 문제가 없네요

emotions = load_dataset("SetFit/emotion")  --> emotions = load_dataset("emotion")

**Comment by rickiepark** [comment]
emotion 데이터셋 다운로드에 문제가 있었는데 해결되었군요. 코드를 바꾸어 정상 작동되는 것을 확인했습니다. 알려 주셔서 감사합니다!
