### ISSUE TITLE
7장 Exception: Failed to install base requirements 오류

### ISSUE THREAD

**Issue by knlpscience** [rickiepark/nlp-with-transformers#3]
install_requirements(chapter=7.2) 부분 실행시 제목과 같은 오류가 떠서 진행이 되질 않습니다..!

![image](https://github.com/rickiepark/nlp-with-transformers/assets/129038718/ea777550-7a61-4415-9566-cec2e74e685e)

**Comment by rickiepark** [comment]
안녕하세요. 해당 오류는 farm-haystack의 1.4 버전이 현재 코랩의 파이토치 버전과 맞지 않기 때문에 발생하는 문제입니다. 적절한 버전을 찾으려면 시간이 좀 소요될 것 같네요. 감사합니다.

**Comment by knlpscience** [comment]
> 안녕하세요. 해당 오류는 farm-haystack의 1.4 버전이 현재 코랩의 파이토치 버전과 맞지 않기 때문에 발생하는 문제입니다. 적절한 버전을 찾으려면 시간이 좀 소요될 것 같네요. 감사합니다.

넵 감사합니다! 😊

**Comment by rickiepark** [comment]
haystack 1.7.0 버전에서 정상 실행되도록 업데이트했습니다. 확인해 보세요. 감사합니다!

**Comment by knlpscience** [comment]
해당 line은 통과하였지만 CUDA버전과 호환이 안되는 것 같습니다. 이런 경우 어떻게 해결해야 될까요? 😂
![image](https://github.com/rickiepark/nlp-with-transformers/assets/129038718/7a3c0f3a-8496-45ec-b62f-e436e066e707)

버전은 다음 처럼 나옵니다!
![image](https://github.com/rickiepark/nlp-with-transformers/assets/129038718/1c40b6f3-60cd-4301-9cd1-bf7dbeab18db)

빠르게 도와주셔서 감사드립니다.

**Comment by rickiepark** [comment]
이상하네요. 저는 에러가 나지 않는데요. 다음 노트북을 한번 실행해 보시겠어요?
https://colab.research.google.com/github/rickiepark/nlp-with-transformers/blob/main/07_question-answering_v2.ipynb

**Comment by knlpscience** [comment]
엇 링크주신 노트북에서 바로 실행하면 문제없이 잘 실행되네요. 
사본으로 실행시키면 여전히 에러가 나는데 어떤 차이가 생기는건지 잘 모르겠습니다,,

**Comment by knlpscience** [comment]
런타임 GPU를 A100을 사용중이었는데 V100으로 바꾸니 해결되었습니다. 
찾아보니 A100은 torch 1.7.0이상 CUDA 11.0이상에서만 호환이 되어서 그렇다고 하는거 같아요.
아무쪼록 도와주셔서 감사드립니다.
